Repository wsu-cpts489-fa20/bp-accreditaid, pull requests merged in 2020-12, with the labels that each got.

#21 Bugfix: Accounts no longer are only of the type 'Instructor'
  client/src/components/LoginPage/CreateEditAccountDialog.js
Labels: Bugfixes

#28 M4: Evaluator page
  client/src/AppMode.js
  client/src/components/AdminPage/AdminPage.jsx
  client/src/components/App.js
  client/src/components/CourseInfo/CourseDeliverablesTab.jsx
  client/src/components/CourseInfo/CourseFilesTab.jsx
  client/src/components/CourseInfo/CourseInfo.jsx
  client/src/components/CourseInfo/CourseMaterialsTab.jsx
  client/src/components/CourseInfo/CourseReadingsTab.jsx
  client/src/components/CourseInfo/ViewDeliverable.jsx
  client/src/components/CoursesPage/Courses.js
  client/src/components/CoursesPage/CoursesForm.js
  client/src/components/CoursesPage/CoursesTable.js
  client/src/components/CoursesPage/Deliverables.js
  client/src/components/CoursesPage/EvaluatorView.jsx
  client/src/components/EmailModal/EmailModal.jsx
  client/src/components/FeedPage/FeedPage.js
  client/src/components/ProgramsPage/PerformanceIndicator.js
  client/src/components/ProgramsPage/ProgramForm.js
  client/src/components/ProgramsPage/Programs.js
  client/src/components/ProgramsPage/StudenOutcomesList.js
  client/src/components/common/FloatingButton.js
  client/src/components/common/ModeBar.js
  client/tests/EvaluatorTests.gif
  client/tests/EvaluatorTests.js
  server/schemas/Course.js
Labels: enhancement

#29 Added comments and removed console.log statements from EvaluatorView.jsx
  client/src/components/CoursesPage/EvaluatorView.jsx
Labels: documentation

#33 Fixing Upload function signatures
  client/src/components/CourseInfo/CourseMaterialsTab.jsx
  client/src/components/CourseInfo/CourseReadingsTab.jsx
  client/src/components/CourseInfo/ViewDeliverable.jsx
Labels: Bugfixes

#35 Back button fix for admins
  client/src/components/App.js
  client/src/components/common/NavBar.js
Labels: bug

#36 Fixed back button for instructors
  client/src/components/common/NavBar.js
Labels: bug
